import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './app.css'
import '@/app/globals.css';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Foodopedia',
  description: 'Generated by Next.js, MongoDB, Browser Barcode Detection API, USDA and OpenFoodFacts APIs, Tailwind and hosted on Vercel',
  icons: '/favicon.ico',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
      </body>
    </html>
  )
}
